hantek_6022be.c: Fix build error.
Drop handle_get_descriptor(), since it's already provided by
fx2lib/lib/setupdat.c, in order to fix the following linker error:

  Multiple definition of _handle_get_descriptor
  Makefile:925: recipe for target 'hw/hantek-6022be/hantek-6022be.ihx' failed